require 'net/http'
require 'uri' 
require "pry"
require 'sqlite3'
require 'active_support'
require 'active_support/core_ext'
require './models/application_record'
require './models/player'
require './models/database'
